module.exports = {
    GET_ORGANIZATIONS: 'get-organizations',
    ADD_ORGANIZATION: 'add-organization',
    UPDATE_ORGANIZATION: 'update-organization',
    DELETE_ORGANIZATION: 'delete-organization',
    GET_PROJECTS: 'get-projects',
    ADD_PROJECT: 'add-project',
    UPDATE_PROJECT: 'update-project',
    DELETE_PROJECT: 'delete-project',
    GET_TASKS: 'get-tasks',
    ADD_TASK: 'add-task',
    UPDATE_TASK: 'update-task',
    DELETE_TASK: 'delete-task',
    SAVE_TIME_ENTRY: 'save-time-entry',
    GET_TIME_ENTRIES: 'get-time-entries',
    UPDATE_TIME_ENTRY: 'update-time-entry',
    DELETE_TIME_ENTRY: 'delete-time-entry',
    GET_LATEST_TIME_ENTRY: 'get-latest-time-entry',
    GET_TOTAL_DURATION_BY_TASK: 'get-total-duration-by-task',
    TOGGLE_DARK_MODE: 'toggle-dark-mode',
};